<?php

namespace EB\PretControleurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnementRepository extends EntityRepository
{
	public function countAbonnemntByUser($user)
  	{
    	$query = $this->createQueryBuilder('a')
        	          ->select('COUNT(a)')  
            	      ->where('a.user = :user')
                	  ->andWhere('a.enCours = true')
        	          ->setParameter('user', $user);
           
  		return $query->getQuery()->getSingleScalarResult();
  	}

	public function countAbonnemntByCentre($centre)
  	{
    	$query = $this->createQueryBuilder('a')
        	          ->where('a.centre = :centre')
        			  ->setParameter('centre', $centre)
        		      ->getQuery()
        			  ->getResult();
  	}
}
