<?php

namespace EB\PretControleurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CentreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentreRepository extends EntityRepository
{
  public function LstCentreByUser($user)
  {
    return  $this->createQueryBuilder('a')
        //->leftJoin('a.centre', 'c')
        ->where('a.user = :user ')
        ->setParameter('user', $user)
        ->getQuery()
        ->getResult();
  }

  public function LstCentreByUserQb($user)
  {
      $qb = $this->createQueryBuilder('a');   
      $qb->where('a.user = :user')
         ->setParameter('user', $user);
      return $qb;
  }
}
