<?php

namespace EB\PretControleurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CentreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentreRepository extends EntityRepository
{
  public function LstCentreByUser($user)
  {
    return  $this->createQueryBuilder('a')
        //->leftJoin('a.centre', 'c')
        ->where('a.user = :user ')
        ->setParameter('user', $user)
        ->getQuery()
        ->getResult();
  }

  public function LstCentreByUserQb($user)
  {
    $qb = $this->createQueryBuilder('a');   
    $qb->where('a.user = :user')
       ->setParameter('user', $user);
    return $qb;
  }

  // retouen la liste de tous les centres pas encore validé,liste destiné à la partie administration
  public function LstCentreInValide()
  {
    return  $this->createQueryBuilder('a')
                 -> where('a.statut = false')
                 ->getQuery()
                 ->getResult();
  }

  // retouen la liste de tous les centres validé,liste destiné à la partie administration
  public function LstCentreValide()
  {
    return  $this->createQueryBuilder('a')
                 -> where('a.statut = true')
                 ->getQuery()
                 ->getResult();
  }

  // retouen la liste de tous mes centres,liste destiné à la partie administration
  public function LstAllCentre()
  {
    return  $this->createQueryBuilder('a')
                 ->orderBy('a.statut','DESC')
                 ->getQuery()
                 ->getResult();
  }

  //retourne la liste deroulante de tous les centre dont le statut est true, liste destiné a la partie abonnement
  public function LstCentreQb()
  {
    $qb = $this->createQueryBuilder('a');   
    $qb -> where('a.statut = true');
    return $qb;
  }
}
