<?php

namespace EB\PretControleurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DepartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementRepository extends EntityRepository
{
	public function getDepartementQueryBuilder($region)
    {
      return $this
      ->createQueryBuilder('a')
      ->where('a.region = :region')
      ->setParameter('region', $region)
    ;
   }

   public function getDepartementByIdQueryBuilder($idRegion)
    {
   	  $qb = $this->createQueryBuilder('a');
      return $qb->where('a.region.id = :region.id')
                ->setParameter('region.id', $idRegion)
                ->getQuery()
                ->getArrayResult();
   }

}
