<?php

namespace EB\PretControleurBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * DisponibiliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisponibiliteRepository extends EntityRepository
{
  public function LstDemandeRecu($user)
  {
    return  $this->createQueryBuilder('a')
        ->leftJoin('a.controleur', 'controleur')
        ->leftJoin('controleur.centre', 'centre')
        ->addSelect('controleur')
        ->addSelect('centre')
        ->where('centre.user = :user ')
        ->andWhere('a.centre IS NOT NULL')
        ->setParameter('user', $user)
        ->getQuery()
        ->getResult();
  }

  /**
   * retourne la liste des disponibilitées à l'exception des dispo des centre de l'utilisateur connecté 
   *
   * @param int $page
   * @param int $maxperpage
   * @param string $sortby
   * @return Paginator
   */
  public function LstDispoByUser($user, $codeDep, $page=1, $maxperpage=4,$date)
  {
    $q = $this->createQueryBuilder('d')
            ->leftJoin('d.controleur', 'c')
            ->leftJoin('c.adresse', 'a')
            ->leftJoin('a.departement', 'dep')
            ->leftJoin('c.centre', 'e')
            ->addSelect('c')
            ->where('e.user != :user')
            ->andWhere('dep.code = :code')
            ->andWhere('d.statut = false')
            ->andWhere('d.date >= :date')
            ->orderBy('d.date','DESC')
            ->setParameter('user', $user)
            ->setParameter('code', $codeDep)
            ->setParameter('date', $date->format('Y-m-d'));

    $q->setFirstResult(($page-1) * $maxperpage)
      ->setMaxResults($maxperpage);
 
    return new Paginator($q);
  }

  public function countDispos($user, $codeDep)
  {
    $query = $this->createQueryBuilder('a')
                  ->select('COUNT(a)')  
                  ->leftJoin('a.controleur', 'c')
                  ->leftJoin('c.adresse', 'ad')
                  ->leftJoin('ad.departement', 'dep')
                  ->leftJoin('c.centre', 'e')
                  ->where('e.user != :user')
                  ->andWhere('dep.code = :code')
                  ->setParameter('user', $user)
                  ->setParameter('code', $codeDep);
           
  	return $query->getQuery()->getSingleScalarResult();
  }

}
