eb_pret_controleur_homepage:
    path:     /
    defaults: { _controller: EBPretControleurBundle:Accueil:index }
eb_pret_controleur_contact:
    path:     /contact
    defaults: { _controller: EBPretControleurBundle:contact:index }
eb_pret_controleur_Administration:
    path:     /Administration
    defaults: { _controller: EBPretControleurBundle:Administration:index }
eb_pret_controleur_Abonnement:
    path:     /Administration/abonnement
    defaults: { _controller: EBPretControleurBundle:Abonnement:index }
eb_pret_controleur_AjoutAbonnement:
    path:     /Administration/abonnement/ajout
    defaults: { _controller: EBPretControleurBundle:Abonnement:ajout }
eb_pret_controleur_Administration_Controleur:
    path:     /Administration/controleur
    defaults: { _controller: EBPretControleurBundle:Administration:indexControleur }
eb_pret_controleur_Administration_Centre:
    path:     /Administration/centre
    defaults: { _controller: EBPretControleurBundle:Administration:indexCentre }
eb_pret_controleur_Administration_EditCentre:
    path:     /Administration/centre/edit/{id}
    defaults: { _controller: EBPretControleurBundle:Administration:edit }
    requirements:
        id: \d+
eb_pret_controleur_emprunter:
    path:     /Gestion/emprunter
    defaults: { _controller: EBPretControleurBundle:Emprunter:index }
eb_pret_controleur_Region:
    path:     /region/ajout
    defaults: { _controller: EBPretControleurBundle:Region:index }
eb_pret_controleur_AjoutRegion:
    path:     /region/ajout
    defaults: { _controller: EBPretControleurBundle:Region:ajout }
eb_pret_controleur_AjoutDepartement:
    path:     /departement/ajout
    defaults: { _controller: EBPretControleurBundle:Departement:ajout }
eb_pret_controleur_Centre:
    path:     /Gestion/centre
    defaults: { _controller: EBPretControleurBundle:Centre:index }
eb_pret_controleur_AjoutCentre:
    path:     /Gestion/centre/ajout
    defaults: { _controller: EBPretControleurBundle:Centre:ajout }
eb_pret_controleur_EditCentre:
    path:     /Gestion/centre/edit/{id}
    defaults: { _controller: EBPretControleurBundle:Centre:edit }
    requirements:
        id: \d+
eb_pret_controleur_ResponsableCentre:
    path:     /responsable/ajout
    defaults: { _controller: EBPretControleurBundle:Responsable:ajout }
eb_pret_controleur_AjoutAdresse:
    path:     /adresse/ajout
    defaults: { _controller: EBPretControleurBundle:Adresse:ajout }
eb_pret_controleur_Controleur:
    path:     /Gestion/controleur
    defaults: { _controller: EBPretControleurBundle:Controleur:index }
eb_pret_controleur_AjoutControleur:
    path:     /Gestion/controleur/ajout
    defaults: { _controller: EBPretControleurBundle:Controleur:ajout }
eb_pret_controleur_EditControleur:
    path:     /Gestion/controleur/edit/{id}
    defaults: { _controller: EBPretControleurBundle:Controleur:edit }
    requirements:
        id: \d+
eb_pret_controleur_ErreurAbonnement:
    path:     /Gestion/disponibilite/erreur/abonnement
    defaults: { _controller: EBPretControleurBundle:Abonnement:erreurAbonnement}
    requirements:
        idDisponibilite: \d+
eb_pret_controleur_DemandeRecuControleur:
    path:     /Gestion/disponibilite/demande/liste
    defaults: { _controller: EBPretControleurBundle:Disponibilite:demandeRecu }
eb_pret_controleur_ReponseDemandeDisponibilite:
    path:     /Gestion/disponibilite/demande/reponse/{idDisponibilite}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:ReponseDispo }
    requirements:
        idControleur: \d+
eb_pret_controleur_AjoutDisponibilite:
    path:     /Gestion/disponibilite/ajout/{idControleur}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:ajout }
    requirements:
        idControleur: \d+
eb_pret_controleur_ListeDisponibilite:
    path:     /Gestion/disponibilite/liste/{departement}/{page}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:listDispo, page: 1}
    options:
        expose: true
eb_pret_controleur_Disponibilite:
    path:     /Gestion/disponibilite/{idControleur}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:index }
    requirements:
        idControleur: \d+
eb_pret_controleur_EditDisponibilite:
    path:     /Gestion/disponibilite/edit/{idDisponibilite}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:edit }
    requirements:
        idDisponibilite: \d+
eb_pret_controleur_DetailDisponibilite:
    path:     /Gestion/disponibilite/detailControleur/{idDisponibilite}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:PriseDispo}
    requirements:
        idDisponibilite: \d+
eb_pret_controleur_ListDepParRegion:
    path:     /ListDepartement
    defaults: { _controller: EBPretControleurBundle:Departement:lstdep }
    options:
        expose: true
eb_pret_controleur_DepByRegion:
    pattern:   /adresse/rempliProduct/{regionId}
    defaults: { _controller: EBPretControleurBundle:Adresse:rempliProduct }
    options:
        expose: true
