eb_pret_controleur_homepage:
    path:     /
    defaults: { _controller: EBPretControleurBundle:Accueil:index }
eb_pret_controleur_contact:
    path:     /contact
    defaults: { _controller: EBPretControleurBundle:contact:index }
eb_pret_controleur_Administration:
    path:     /administration/centre/liste-des-centres-de-controle-technique-a-valide
    defaults: { _controller: EBPretControleurBundle:Administration:index }
eb_pret_controleur_Gestion_TableauBord:
    path:     /gestion/tableau-de-bord
    defaults: { _controller: EBPretControleurBundle:TableauBord:index }
eb_pret_controleur_Administration_TableauBord:
    path:     /administration/tableau-de-bord
    defaults: { _controller: EBPretControleurBundle:TableauBord:indexAdmin }
eb_pret_controleur_Abonnement:
    path:     /administration/abonnement/liste-des-abonnements
    defaults: { _controller: EBPretControleurBundle:Abonnement:index }
eb_pret_controleur_AjoutAbonnement:
    path:     /administration/abonnement/ajouter-un-abonnement-pour-un-centre-de-controle-technique
    defaults: { _controller: EBPretControleurBundle:Abonnement:ajout }
eb_pret_controleur_SupprimerAbonnement:
    path:     /administration/abonnement/supprimer-un-abonnement-pour-un-centre-de-controle-technique/{idAbonnement}
    defaults: { _controller: EBPretControleurBundle:Abonnement:supprimer }
    requirements:
        idAbonnement: \d+
eb_pret_controleur_Administration_Centre:
    path:     /administration/centre/liste-des-centres-de-controle-technique-valide
    defaults: { _controller: EBPretControleurBundle:Administration:indexCentre }
eb_pret_controleur_Administration_EditCentre:
    path:     /administration/centre/valider-un-centre-de-controle-technique/{id}/{lstValide}
    defaults: { _controller: EBPretControleurBundle:Administration:edit }
    requirements:
        id: \d+
eb_pret_controleur_Administration_ListeCentreValide:
    path:     /administration/controleur/choisir-centre-de-controle-technique-pour-valider-ses-controleurs
    defaults: { _controller: EBPretControleurBundle:Administration:listeCentreValideForValideControleur }
eb_pret_controleur_Administration_Controleur:
    path:     /administration/controleur/liste-des-controleurs-a-valide/{id}
    defaults: { _controller: EBPretControleurBundle:Administration:indexControleur }
    requirements:
        id: \d+   
eb_pret_controleur_Administration_EditControleur:
    path:     /administration/controleur/valider-un-controleur/{id}
    defaults: { _controller: EBPretControleurBundle:Administration:editControleur }
    requirements:
        id: \d+  
eb_pret_controleur_Administration_EmpruntTraite:
    path:     /administration/suivi/liste-des-emprunt-de-controleur-traite
    defaults: { _controller: EBPretControleurBundle:Administration:indexEmpruntTraite }
eb_pret_controleur_Administration_EmpruntAVenir:
    path:     /administration/suivi/liste-des-emprunt-emprunt-a-venir
    defaults: { _controller: EBPretControleurBundle:Administration:indexEmpruntAVenir }
eb_pret_controleur_Administration_EnvoieQuestionnaire:
    path:     /administration/suivi/emprunt-traite/envoie-questionnaire/{idDisponibilite}
    defaults: { _controller: EBPretControleurBundle:Administration:EnvoieMailQuestionnaire }
    requirements:
        id: \d+  
eb_pret_controleur_emprunter:
    path:     /choisir-le-departement-du-controleur-rechercher
    defaults: { _controller: EBPretControleurBundle:Emprunter:index }
eb_pret_controleur_Region:
    path:     /region/ajout
    defaults: { _controller: EBPretControleurBundle:Region:index }
eb_pret_controleur_AjoutRegion:
    path:     /region/ajout
    defaults: { _controller: EBPretControleurBundle:Region:ajout }
eb_pret_controleur_AjoutDepartement:
    path:     /departement/ajout
    defaults: { _controller: EBPretControleurBundle:Departement:ajout }
eb_pret_controleur_Centre:
    path:     /gestion/centre/liste-centre-controle-technique
    defaults: { _controller: EBPretControleurBundle:Centre:index }
eb_pret_controleur_AjoutCentre:
    path:     /gestion/centre/ajouter-centre-controle-technique
    defaults: { _controller: EBPretControleurBundle:Centre:ajout }
eb_pret_controleur_EditCentre:
    path:     /gestion/centre/editer-un-centre-controle-technique/{id}
    defaults: { _controller: EBPretControleurBundle:Centre:edit }
    requirements:
        id: \d+
eb_pret_controleur_ResponsableCentre:
    path:     /responsable/ajout
    defaults: { _controller: EBPretControleurBundle:Responsable:ajout }
eb_pret_controleur_AjoutAdresse:
    path:     /adresse/ajout
    defaults: { _controller: EBPretControleurBundle:Adresse:ajout }
eb_pret_controleur_Controleur:
    path:     /gestion/controleur/liste-de-controleurs
    defaults: { _controller: EBPretControleurBundle:Controleur:index }
eb_pret_controleur_AjoutControleur:
    path:     /gestion/controleur/ajouter-un-controleur
    defaults: { _controller: EBPretControleurBundle:Controleur:ajout }
eb_pret_controleur_EditControleur:
    path:     /gestion/controleur/editer-un-controleur/{id}
    defaults: { _controller: EBPretControleurBundle:Controleur:edit }
    requirements:
        id: \d+
eb_pret_controleur_ErreurAbonnement:
    path:     /gestion/disponibilite/erreur/abonnement
    defaults: { _controller: EBPretControleurBundle:Abonnement:erreurAbonnement}
    requirements:
        idDisponibilite: \d+
eb_pret_controleur_DemandeRecuControleur:
    path:     /gestion/disponibilite/liste-des-demandes-de-reservation-recu-pour-vos-controleurs
    defaults: { _controller: EBPretControleurBundle:Disponibilite:demandeRecu }
eb_pret_controleur_DemandeValideControleur:
    path:     /gestion/disponibilite/liste-des-demandes-de-reservation-controleur-validee
    defaults: { _controller: EBPretControleurBundle:Disponibilite:demandeValide }
eb_pret_controleur_DemandeNonValideControleur:
    path:     /gestion/disponibilite/liste-des-demandes-de-reservation-controleur-en-cours-de-validation
    defaults: { _controller: EBPretControleurBundle:Disponibilite:demandeNonValide }
eb_pret_controleur_ControleurReserveControleur:
    path:     /gestion/disponibilite/liste-de-mes-controleurs-reserver-ou-non
    defaults: { _controller: EBPretControleurBundle:Disponibilite:controleurReserverValide }
eb_pret_controleur_ReponseDemandeDisponibilite:
    path:     /gestion/disponibilite/demande/reponse/{idDisponibilite}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:reponseDispo }
    requirements:
        idControleur: \d+
eb_pret_controleur_AnnulerDemandeDisponibilite:
    path:     /gestion/disponibilite/demande/annuler/{idDisponibilite}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:annulerDemandeValide }
    requirements:
        idControleur: \d+
eb_pret_controleur_AnnulerDemandeNonValideDisponibilite:
    path:     /gestion/disponibilite/demande-non-valider/annuler/{idDisponibilite}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:annulerDemandeNonValide }
    requirements:
        idControleur: \d+
eb_pret_disponibilite_ListeControleur:
    path:     /gestion/disponibilite/choisir-controleur-pour-ajouter-disponibilite
    defaults: { _controller: EBPretControleurBundle:Disponibilite:ListeControleur }
eb_pret_controleur_AjoutDisponibilite:
    path:     /gestion/disponibilite/ajouter-date-disponibilite-pour-un-controleur/{idControleur}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:ajout }
    requirements:
        idControleur: \d+
eb_pret_controleur_AjoutCreneauDisponibilite:
    path:     /gestion/disponibilite/ajouter-un-creneau-pour-un-controleur/{idControleur}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:ajoutCreneau }
    requirements:
        idControleur: \d+
eb_pret_controleur_ListeDisponibilite:
    path:     /rechercher/liste-des-controleurs-disponible/{departement}/{page}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:listDispo, page: 1}
    options:
        expose: true
eb_pret_controleur_Disponibilite:
    path:     /gestion/disponibilite/liste-date-disponibilite-par-controleur/{idControleur}/{page}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:index, page: 1 }
    requirements:
        idControleur: \d+
eb_pret_controleur_EditDisponibilite:
    path:     /gestion/disponibilite/editer-date-disponibilite-pour-un-controleur/{idDisponibilite}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:edit }
    requirements:
        idDisponibilite: \d+
eb_pret_controleur_DetailDisponibilite:
    path:     /gestion/disponibilite/detailControleur/{idDisponibilite}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:PriseDispo}
    requirements:
        idDisponibilite: \d+
eb_pret_controleur_DetailDisponibiliteByControleur:
    path:     /rechercher/emprunter-reserver-un-controleur/{idControleur}/{nbJoursDispo}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:DispoByControleur}
    requirements:
        idControleur: \d+
eb_pret_controleur_ListDepParRegion:
    path:     /ListDepartement
    defaults: { _controller: EBPretControleurBundle:Departement:lstdep }
    options:
        expose: true
eb_pret_controleur_DepByRegion:
    pattern:   /adresse/rempliProduct/{regionId}
    defaults: { _controller: EBPretControleurBundle:Adresse:rempliProduct }
    options:
        expose: true
eb_pret_centre_DepByUser:
    pattern:   /disponibilite/centre/liste-centre-by-user
    defaults: { _controller: EBPretControleurBundle:Disponibilite:lstCentreByUser }
    options:
        expose: true
eb_pret_Disponibilite_ReserverByUser:
    pattern:   /disponibilite/Prise-disponibilite-by-Users/{dispoId}/{centreId}/{statut}/{pris}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:priseDispoByUser }
    options:
        expose: true
eb_pret_Disponibilite_AjoutCreneau:
    pattern:   /disponibilite/ajouter-un-creneau-pour-un-controleur/{idControleur}/{dateDebut}/{dateFin}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:ajoutCreneauControleur }
    requirements:
        idControleur: \d+
        dateDebut: ".+"
        dateFin: ".+"
    options:
        expose: true
eb_pret_controleur_NbDispoParRegion:
    pattern:   /disponibilite/calculNbControleurDispoParRegion/{departement}
    defaults: { _controller: EBPretControleurBundle:Disponibilite:calculNbControleurDispoParRegion }
    options:
        expose: true

