# src/EB/EbPretControlleurBundle/Resources/config/validation.yml
EB\PretControleurBundle\Entity\Adresse:
    properties:
        codePostal:
            - Regex:
                pattern: "/^0[1-9]|[1-8][0-9]|9[0-8]|2A|2B[0-9]{3}$/"
                match:   true
                message: Veuillez saisir un code postal correct.
EB\PretControleurBundle\Entity\Controleur:
    properties:
        numAgrement:
            - Regex:
                pattern: "/([0-9]{3})([A-Z]{1})([0-9]{4})/"
                match:   true
                message: Votre numéro d'agrement n'est pas valide.
        email:
            - Email:
                message: "'{{ value }}' n'est pas un email valide."
                checkMX: true
        telephone:
            - Regex:
                pattern: "/([0-9]{10})/"
                match:   true
                message: Veuillez saisir un numéro de téléphone valide.
        experience:
            - Regex:
                pattern: "/[0-9]{0,2}/"
                match:   true
                message: Veuillez saisir une expérience valide.
EB\PretControleurBundle\Entity\Centre:
    properties:
        siret:
            - Regex:
                pattern: "/([0-9]{14})/"
                match:   true
                message: Votre numéro de siret n'est pas valide.   
        numAgrement:
            - Regex:
                pattern: "/([A-Z]{1})([0-9]{3})([A-Z]{1})([0-9]{3})/"
                match:   true
                message: Votre numéro d'agrement n'est pas valide.
        email:
            - Email:
                message: "'{{ value }}' n'est pas un email valide."
                checkMX: true
        telephone:
            - Regex:
                pattern: "/([0-9]{10})/"
                match:   true
                message: Veuillez saisir un numéro de téléphone valide.
EB\UserBundle\Entity\User:
    properties:
        numAgrement:
            - Regex:
                pattern: "/([A-Z]{1})([0-9]{3})([A-Z]{1})([0-9]{3})/"
                match:   true
                message: Votre numéro d'agrement n'est pas valide.